services:
  - type: web
    name: mern-advance-auth
    env: node
    buildCommand: npm run render-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAILTRAP_TOKEN
        sync: false
      - key: CLIENT_URL
        value: https://mern-advance-auth.onrender.com
      - key: NODE_ENV
        value: production